workflow actualizado para que limpie antes de compilar y que compruebe que se ha creado el binario después de compilar

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,7 +16,19 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Install dependencies
-        run: sudo apt-get update && sudo apt-get install -y build-essential libreadline-dev
+        run:  |
+          sudo apt-get update
+          sudo apt-get install -y build-essential libreadline-de
+
+      - name: Clean previous builds
+        run: make fclean || true
 
       - name: Compile project
         run: make
+
+      - name: Check output binary
+        run:  |
+          if [ ! -f minishell ]; then
+            echo "❌ Error: No se ha generado el ejecutable minishell"
+            exit 1
+          fi
